default:
  image: eclipse-temurin:8-jre-alpine

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_CLI_OPTS: >-
    -DskipTests

build-JAR:
  stage: build
  script:
    - './mvnw $MAVEN_CLI_OPTS package'

test-code:
  stage: test
  script:
    - './mvnw test'

deploy:
  stage: deploy
  script:
    - './mvnw deploy -s ci_settings.xml'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
