name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  packages: write

env:
  JAVA_VERSION: 21
  PROJECT_NAME: SCIMple
  PROJECT_NAME_LOWER: scimple

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0 # need history to generate the changelog

      - name: Set up Java ${{ env.JAVA_VERSION }}-zulu
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 #v4.7.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: zulu
          cache: maven
      - name: Build and publish Maven artifacts
        run: ./mvnw deploy --batch-mode --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
